name: Checks

on:
  push:

env:
  TFLINT_VERSION: "v0.53.0"
  TFDOCS_VERSION: "v0.19.0"
  PYTHON_VERSION: "3.13"

jobs:
  precommit:
    name: Run precommit-hooks
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}

      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.23.0"

      - name: Setup terraform-docs
        run: go install github.com/terraform-docs/terraform-docs@${{ env.TFDOCS_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: pre-commit/action@v3.0.1
